name = "attemp6"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MCC_atTop_eq_FM"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "MCC_atTop_eq_FM"
